### ISSUE TITLE
Uncaught SyntaxError: Unexpected token C in JSON at position 7518

### ISSUE THREAD

**Issue by beansrowning** [REditorSupport/atom-ide-r#5]
Possibly related to #4 

### Steps to reproduce  

1. R version 3.5.0
2. language-server 0.2.2
3. Have a few files open, and hover mouse over a few functions for documenatation
4. Error eventually thrown
5. Subsequently, more errors thrown every time mouse triggers hoverover documentation:   

```
Error: Header must provide a Content-Length property.
    at SocketMessageReader.StreamMessageReader.onData (C:\Users\xxxx\.atom\packages\ide-r\node_modules\vscode-jsonrpc\lib\messageReader.js:200:27)
    at Socket.<anonymous> (C:\Users\xxxx\.atom\packages\ide-r\node_modules\vscode-jsonrpc\lib\messageReader.js:185:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)
```  

I can't seem to isolate any function documentation in particular that sets it off, but it looks like some function is screwing up the JSON output and causing all subsequent messages to be malformed. 

### Stack Trace

Uncaught SyntaxError: Unexpected token C in JSON at position 7518

```
At file:///C:/Users/xxxx/Atom/resources/app.asar/static/index.html:1

SyntaxError: Unexpected token C in JSON at position 7518
    at JSON.parse (<anonymous>)
    at SocketMessageReader.StreamMessageReader.onData (/packages/ide-r/node_modules/vscode-jsonrpc/lib/messageReader.js:219:29)
    at /packages/ide-r/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)
```

### Commands

```
     -4:56.4.0 settings-view:open (input.hidden-input)
     -4:28.3.0 core:save (input.hidden-input)
  2x -2:18.3.0 core:backspace (input.hidden-input)
     -2:12.3.0 core:save (input.hidden-input)
     -1:35 core:copy (input.hidden-input)
     -1:25.4.0 core:paste (input.hidden-input)
     -1:22.2.0 editor:newline (input.hidden-input)
  4x -1:21.6.0 core:move-right (input.hidden-input)
  3x -1:19 core:backspace (input.hidden-input)
     -0:43.3.0 core:copy (input.hidden-input)
     -0:39 editor:newline (input.hidden-input)
     -0:38.5.0 core:move-up (input.hidden-input)
  7x -0:38.2.0 core:move-right (input.hidden-input)
     -0:36.6.0 core:paste (input.hidden-input)
  3x -0:27.9.0 core:backspace (input.hidden-input)
     -0:23.4.0 core:move-right (input.hidden-input)
```

### Non-Core Packages

```
apex-syntax 0.2.0 
apex-ui 1.0.3 
atom-beautify 0.32.2 
atom-ide-ui 0.11.1 
atom-idle-autosave 0.3.0 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.1 
minimap-hide 0.3.0 
base-16-ocean-dark-ui-theme 1.7.2 
busy-signal 1.4.3 
city-lights-syntax 1.1.4 
city-lights-ui 1.2.0 
dark-flat-ui 1.2.4 
file-icons 2.1.20 
ide-python 0.9.2 
ide-r 0.1.6 
intentions 1.1.5 
language-cuda 0.1.0 
language-fortran 2.1.6 
language-latex 1.1.1 
language-lua 0.9.11 
language-r 0.4.2 
latex 0.50.0 
linter 2.2.0 
linter-lintr 1.1.4 
linter-ui-default 1.7.1 
material-palenight-syntax 1.5.7 
minimap 4.29.8 
outlander-syntax 2.0.0 
pdf-view 0.70.0 
slush-poppies 0.1.1 
unity-ui 2.1.11 
Zen 0.18.0 
```

**Comment by randy3k** [comment]
I cannot reproduce it on my mac though. Could you open the developer console and turn on the debug mode
```
atom.config.set('core.debugLSP', true)
```
See if you could obtain some informative logs there.

**Comment by beansrowning** [comment]
Sounds good, I'll do that.

**Comment by randy3k** [comment]
It seems that it's the function `DBI::dbConnect` which triggers the error. The same function works fine on my mac. Though I just noticed another bug related to the signature help of `DBI::dbConnect`.

**Comment by beansrowning** [comment]
@randy3k Yeah, that looks to be the case. I just tried making a scrap document with just that function and it caused the error.

**Comment by randy3k** [comment]
I suspect that the documentation of `DBI::dbConnect` may contain some invalid characters for windows. Maybe JSON only assume unicode encoding?

Could you try running the following in R?

```r
tools::Rd2txt_options(underline_titles = FALSE)
result <- repr::repr_text(utils::help(dbConnect, DBI))
tools::showNonASCII(result)
Encoding(result)
```

**Comment by randy3k** [comment]
I just pushed https://github.com/REditorSupport/languageserver/commit/4aaf5859a71c746863f2581306c0b9554ed63314 to make sure the documentation is encoded with unicode. See if it helps your issue. Install the latest languageserver by

```
source("https://install-github.me/REditorSupport/languageserver")
```

**Comment by beansrowning** [comment]
@randy3k Here was the output:

```
1: dbConnect                 package:DBI                  R Documentation

Create a connection to a DBMS

Description:

     Connect to a DBMS going through the appropriate authentication
     procedure. Some implementations may allow you to have multiple
     connections open, so you may invoke this function repeatedly
     assigning its output to different objects. The authentication
     mechanism is left unspecified, so check the documentation of
     individual drivers for details.

Usage:

     dbConnect(drv, ...)

Arguments:

     drv: an object that inherits from DBIDriver, or an existing
          DBIConnection object (in order to clone an existing
          connection).

     ...: authentication arguments needed by the DBMS instance; these
          typically include 'user', 'password', 'host', 'port',
          'dbname', etc. For details see the appropriate 'DBIDriver'.

Value:

     'dbConnect()' returns an S4 object that inherits from
     DBIConnection. This object is used to communicate with the
     database engine.

Specification:

     DBI recommends using the following argument names for
     authentication parameters, with 'NULL' default:

        <e2><80><a2> 'user' for the user name (default: current user)

        <e2><80><a2> 'password' for the password

        <e2><80><a2> 'host' for the host name (default: local connection)

        <e2><80><a2> 'port' for the port number (default: local connection)

        <e2><80><a2> 'dbname' for the name of the database on the host, or the
          database file name

     The defaults should provide reasonable behavior, in particular a
     local connection for 'host = NULL'.  For some DBMS (e.g.,
     PostgreSQL), this is different to a TCP/IP connection to
     'localhost'.

See Also:

     'dbDisconnect()' to disconnect from a database.

     Other DBIDriver generics: 'DBIDriver-class', 'dbDataType',
     'dbDriver', 'dbGetInfo', 'dbIsValid', 'dbListConnections'

Examples:

     # SQLite only needs a path to the database. (Here, ":memory:" is a special
     # path that creates an in-memory database.) Other database drivers
     # will require more details (like user, password, host, port, etc.)
     con <- dbConnect(RSQLite::SQLite(), ":memory:")
     con

     dbListTables(con)

     dbDisconnect(con)

[1] "latin1"
```  

I pulled your changes to languageserver, but I still get the same error. It seems like those bullet points are likely causing it though...

**Comment by beansrowning** [comment]
Great work, @randy3k .

I've tested on both of my platforms and this appears to be working as expected.
